### PR TITLE
Hhs implementation

### PR DESCRIPTION
**Pull request by frankcarey**

### CODE REVIEW

**Comment by frankcarey** [comment]
Good stuff, Dan also wants one for group admin pages.

I _think_ I have a way to do this in a generic way for any named entity using more entity_api stuff.

**Comment by frankcarey** [comment]
There are a few issues with this PR as-is before we can merge it:
- The permissions checks are useful, but they don't work properly with selenium driver (which doesn't support response codes for some reason). We should have a backup that looks for an error message or something.
- The use of traits is interesting, I'd like to know more about the plan in using that.
- The addition of custom_fields into the constructor is necessary for HHS right now, but I think the direction we discussed of behat hooks for @BeforeEntitySave and @AfterEntitySave is the better way to go. That branch is still in-progress (turned into much more work than expected, but I think still necessary), I'd expect we can have that done soon, making some of the other items obsolete.

Overall, I think we should prioritize fixing the hook branch, https://github.com/NuCivic/dkanextension/tree/dev-entity-hooks and then look how these features can best be achieved with the latest tools in the extension.

**Comment by rhabbachi** [comment]
@frankcarey 
- Totally agree on the Permissions checks.
- We opted for traits because we added support for HHS only content type that have moderation enabled for it [FeedbackContext](https://github.com/NuCivic/healthdata/blob/master/tests/features/bootstrap/FeedbackContext.php) and we wanted to have the moderation logic encapsulated in a single entity for both Feedback and Dataset classes.
- I agree on the entity alter hooks and I think HHS should migrate to it when available.

**Comment by frankcarey** [comment]
Most of this stuff should be incorporated into dkanextension (workflow, more page tests, etc). The HHS team should try to convert back to the standard extension, then close this PR

**Comment by dkinzer** [comment]
tests pass on data_starter_private: https://circleci.com/gh/NuCivic/data_starter_private/553 so I'm merging

**Comment by dkinzer** [comment]
I'll delete this branch once I confirm that hhs will pass using it.

**Comment by dkinzer** [comment]
Looks like I didn't set up the tests correctly to verity that no harm would happen.  so I reset master to orig ref, til further testing.

**Pull request merged**
