### PR TITLE
Add some hhs related contexts.

### PR DESCRIPTION
**Pull request by dkinzer**
So that we can obliterate the hhs specific implementations.

Not all of these need to stick around for ever.  We just need to include them
here as a first step.

REF CIVIC-3900
# Acceptance Tests
- [ ] does not break data_stater_private tests
- [x] does not break dkan tests

https://github.com/NuCivic/data_starter_private/pull/113

### CODE REVIEW

**Comment by dkinzer** [comment]
@acouch this can be merged.

[...spent some time this morning trying to get rid of hhs dependency on ContextFeature, but was taking too long.  It's not a big deal just would be cleaner since upstream doesn't seem to need it.  Leaving it for another day.]

**Comment by acouch** [comment]
I think the DKANExtension items need to be pulled out and pulled into individual context https://github.com/NuCivic/dkanextension/pull/56/files#diff-387d4d58c7b527ea01919fdf57d701f7R1

**Comment by dkinzer** [comment]
@acouch thanks, I'll do that.

**Comment by dkinzer** [comment]
Change that I made seems to be making one general test timemout.

**Comment by dkinzer** [comment]
third time's the charm... passed.

**Comment by dkinzer** [comment]
Cleaning this whole thing up.

**Pull request closed without merging**
